name: Go API PROJECT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
  
    - name: Install pre-commit hooks
      run: pre-commit install
  
    - name: Run pre-commit hooks
      run: pre-commit run --all-files

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
